#pragma once

#include "hal.h"
#include "samv71.h"

#define MATRIX_MASTER_ID_CORTEX_M7_CODE 0
#define MATRIX_MASTER_ID_CORTEX_M7_USB_HS_EXT_MEM_PERIPH 1
#define MATRIX_MASTER_ID_CORTEX_M7_PERIPHERAL 2
#define MATRIX_MASTER_ID_ICM 3
#define MATRIX_MASTER_ID_DMA_IF0 4
#define MATRIX_MASTER_ID_DMA_IF1 5
#define MATRIX_MASTER_ID_ISI 6
#define MATRIX_MASTER_ID_MEDIALB 7
#define MATRIX_MASTER_ID_USB 8
#define MATRIX_MASTER_ID_GMAC 9
#define MATRIX_MASTER_ID_CAN0 10
#define MATRIX_MASTER_ID_CAN1 11
#define MATRIX_MASTER_ID_CORTEX_M7_QSPI 12

#define MATRIX_SLAVE_SRAM_ICM_DMA_IF0 0
#define MATRIX_SLAVE_SRAM_OTHER_DMA 1
#define MATRIX_SLAVE_ROM 2
#define MATRIX_SLAVE_FLASH 3
#define MATRIX_SLAVE_USB_HS_RAM 4
#define MATRIX_SLAVE_EXT_BUS 5
#define MATRIX_SLAVE_QSPI 6
#define MATRIX_SLAVE_PERIPHERAL_BRIDGE 7
#define MATRIX_SLAVE_CORTEX_M7_AHBS 8

uint32_t matrix_set_periph_master_addr(uint32_t ul_master_id, void *addr);
